name: Check for Linked Issue
on:
  pull_request:
    branches: [ dev ]
    types: [opened, edited, synchronized]

jobs:
  check-link:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Issue Link
        uses: nearform-actions/github-action-check-linked-issues@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-keywords: "fixes, closes, resolves"
          fail-if-no-linked-issue: true
